// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX68ivw-LTpxC2F0thB3VYIz1si-2Oozc',
    appId: '1:256285802720:web:35d78214beb78922769085',
    messagingSenderId: '256285802720',
    projectId: 'tartilin-534af',
    authDomain: 'tartilin-534af.firebaseapp.com',
    storageBucket: 'tartilin-534af.firebasestorage.app',
    measurementId: 'G-L2ZQ11XY0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzpQUF-crLX6AIyAUqT7GDx3vw2oWBYOA',
    appId: '1:256285802720:android:aa952c24ab05a23d769085',
    messagingSenderId: '256285802720',
    projectId: 'tartilin-534af',
    storageBucket: 'tartilin-534af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgbdNTK_gYLIzz--KAVqy56jISI8TkJJk',
    appId: '1:256285802720:ios:9ae8bed11d6f9424769085',
    messagingSenderId: '256285802720',
    projectId: 'tartilin-534af',
    storageBucket: 'tartilin-534af.firebasestorage.app',
    iosBundleId: 'com.example.tartile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgbdNTK_gYLIzz--KAVqy56jISI8TkJJk',
    appId: '1:256285802720:ios:9ae8bed11d6f9424769085',
    messagingSenderId: '256285802720',
    projectId: 'tartilin-534af',
    storageBucket: 'tartilin-534af.firebasestorage.app',
    iosBundleId: 'com.example.tartile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX68ivw-LTpxC2F0thB3VYIz1si-2Oozc',
    appId: '1:256285802720:web:eee7422960677f5d769085',
    messagingSenderId: '256285802720',
    projectId: 'tartilin-534af',
    authDomain: 'tartilin-534af.firebaseapp.com',
    storageBucket: 'tartilin-534af.firebasestorage.app',
    measurementId: 'G-EJ1PLTKFCB',
  );
}
